### ISSUE TITLE
< 5.0 active_record

### ISSUE THREAD

**Issue by kwerle** [khiav223577/in_batches#2]
You might add a limit of active_record < 5.0 to the gemspec so that folks don't continue using this gem after they've upgraded their app...

**Comment by khiav223577** [comment]
Thanks for your suggestion. Maybe adding a warning is more suitable since this gem will do nothing in active_record >= 5.0. And I would like to test this gem in active_record >= 5.0 to make sure the behavior of the gem is the same in active_record  3.2, 4.2, 5.2.

**Comment by khiav223577** [comment]
Almost forgot it. I just released v1.0.1 for this :)
See the changes: https://github.com/khiav223577/in_batches/compare/v1.0.0...v1.0.1
